### ISSUE TITLE
Office / Operations: Apple ID for retired laptops

### ISSUE THREAD

**Issue by patricksimpson** [sparkbox/standard#71]
Going off of what @asimpson started for #48 should we not have an office "generic" Apple ID that is used on all of our retired/loaner laptops? We could easily setup the laptop with this ID and register the mac with `find my ____` etc. We could have different IDs for Apprentices vs general use laptops.

**Comment by cromwellryan** [comment]
I think that might work. I think we'll want to keep the Apple ID login in the operations vault for Nikki though, rather than in the Shared vault.

To clarify the purpose, this is in reference to the missing laptops, instead of purchasing software. This might solve both problems in the shared pool / apprentice laptops, but the former is the trigger to this, correct?

**Comment by patricksimpson** [comment]
@cromwellryan correct & correct!

**Comment by cromwellryan** [comment]
nice - dooo eeet!
